apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/targetWorkloadIds: '["default/docker-registry-ui"]'
    management.cattle.io/ui-managed: 'true'
  name: docker-registry-ui
  namespace: default
  ownerReferences:
    - apiVersion: apps/v1
      controller: true
      kind: Deployment
      name: docker-registry-ui
      uid: b54ad288-266e-463f-8854-5b1c7ab3ed02
  resourceVersion: '441210'
  uid: c581c49c-acf5-4f2d-a3c8-ead779f4b674
spec:
  clusterIP: 10.43.145.168
  clusterIPs:
    - 10.43.145.168
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
    - name: https
      port: 443
      protocol: TCP
      targetPort: 443
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-default-docker-registry-ui
  sessionAffinity: None
  type: ClusterIP