apiVersion: v1
data:
  nailloux.crt: |
    -----BEGIN CERTIFICATE-----
    MIIFtzCCA5+gAwIBAgIUN/u1o/hVyzOeqZwXZQAhb5nPhpwwDQYJKoZIhvcNAQEL
    BQAwazELMAkGA1UEBhMCRlIxFjAUBgNVBAgMDUhhdXRlLUdhcm9ubmUxETAPBgNV
    BAcMCE5haWxsb3V4MRowGAYDVQQKDBFDbHViUGhvdG9OYWlsbG91eDEVMBMGA1UE
    AwwMbmFpbGxvdXgubGFuMB4XDTI1MTEwMzEzMjIwNloXDTI2MTEwMzEzMjIwNlow
    azELMAkGA1UEBhMCRlIxFjAUBgNVBAgMDUhhdXRlLUdhcm9ubmUxETAPBgNVBAcM
    CE5haWxsb3V4MRowGAYDVQQKDBFDbHViUGhvdG9OYWlsbG91eDEVMBMGA1UEAwwM
    bmFpbGxvdXgubGFuMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA0BJe
    Rb590j3bWd2noBnMPKZcuSqHFC0uyB0/kwQO6qsugKVed6zuJhtSsTHNsEr2IytN
    ayYfl6jT2FkzOkP6gJvrHHTc/PpHJuzP0sP1eQDVfq8DWtYBlsF8zPsoLoKhHSlC
    2yVl9AQ2tgrOnjmTBmATsLhLghkiBDgebrH8TA/he0N++4kEl9NhCptFUwgr1xk0
    sThokgvmaWBzMgPuE8YMChRWB6K9V3T74bbpDJMghEpL0KXjOLWZ+HLi5UU/SvTM
    8bp6W8NjAcyUua3MNws/e7g6ytQ+0EOwrJFgen3Ko5vVSlzOPASCYHyEk6Sy+Rdk
    aPG3vbjljf8vM5IMzwOCSH5KhiruZreKuORQqBwcGnX+tN5cq0ryGHeLpZblx5Fq
    QSXg/04ueyhq8pwm4EEh7UNLBRV5udeFrPine9ANqEFx2tOpD8uyIAngr6+RH4/V
    ZroYCVH5/kMVzd26AuJcy+R8pjYtgieMDBtge7O/RPT3Fog9AourXKQSViOlnfrq
    nDbVkEKtVxgsdKS3BFJO8GPHpYlYatkq0Ba2EZ4LFLLYr5r7yZHcqWPeYKSNJzGK
    ETkUBLn4QUzgEUe/FuaYDqyFLJQEs3RBMoDt6xT1KhxEWN3IjvXBpyMVXhfmL6fL
    FnYOOluflSKp/hieHGGv1ajhFPK6sPN4mp4/GMkCAwEAAaNTMFEwHQYDVR0OBBYE
    FEqenXZUDVLijaSSpFiRAdmIDpX8MB8GA1UdIwQYMBaAFEqenXZUDVLijaSSpFiR
    AdmIDpX8MA8GA1UdEwEB/wQFMAMBAf8wDQYJKoZIhvcNAQELBQADggIBAA6ZJZGF
    5vwJVeIoF3ibEiR/B+k4lx+1S4LMUxqXFa7NtKmIKABhQ6ZKL3XeHX3XYLAYvsC5
    sj9BfD7Yj41zzVlSB0jPPNAjz+8/skMvfNOpwmJx48pgL6yvFRYdI7M+XewY7DG1
    N43uvV+NdcDJ5gtP0fw3YchzdiNDPw7j3OQ4EYp85oP8dW0omT1p9kISut3XDRXM
    NULoPIO+QKgX57fBfHt4TccHYcIZnU/9Gm75MIGWgVaBvYKZT0/PFi9mtU2cR6fG
    wg7CfOqRwFzd8vu+CbSyuNaXLHuzF5aMf+P/68qjUkifz+crRPcKcqM6Nzr8wm6I
    RjAmiOgdmKHfq7it6tva3MnA3gA+tFWDJjGmJarM+9evksGIzfYVakhkWqQ7OWnu
    oVRuMWEAyyQ85IqIvDIkthWM7HxnFbeNGMYJG0y7xVVHOcWGWx0enrQLSbOC1H+4
    DrYQQAx36mTN0uZ8PFiwDLnzuyeNRlqoSzPcJ/dd2d/iLfBZIUJz/s5NWGo9GeeL
    lY8hOImFbK8wJoNJxzd0BJ2A6V5VXOg7EozR5aRfNK8nMCGm2mrv7KzKR0E43U4m
    8QMClUKxe/xM+4+JX25pczfXcL3B/pQQQOMOFC/NiDksZnh/RqEyvbbFKxonKGlS
    r2lw6ahd4i7ouuMqQHgAI6DrWvmv2DKNGPGA
    -----END CERTIFICATE-----
  nailloux.key: |
    -----BEGIN PRIVATE KEY-----
    MIIJQwIBADANBgkqhkiG9w0BAQEFAASCCS0wggkpAgEAAoICAQDQEl5Fvn3SPdtZ
    3aegGcw8ply5KocULS7IHT+TBA7qqy6ApV53rO4mG1KxMc2wSvYjK01rJh+XqNPY
    WTM6Q/qAm+scdNz8+kcm7M/Sw/V5ANV+rwNa1gGWwXzM+ygugqEdKULbJWX0BDa2
    Cs6eOZMGYBOwuEuCGSIEOB5usfxMD+F7Q377iQSX02EKm0VTCCvXGTSxOGiSC+Zp
    YHMyA+4TxgwKFFYHor1XdPvhtukMkyCESkvQpeM4tZn4cuLlRT9K9Mzxunpbw2MB
    zJS5rcw3Cz97uDrK1D7QQ7CskWB6fcqjm9VKXM48BIJgfISTpLL5F2Ro8be9uOWN
    /y8zkgzPA4JIfkqGKu5mt4q45FCoHBwadf603lyrSvIYd4ulluXHkWpBJeD/Ti57
    KGrynCbgQSHtQ0sFFXm514Ws+Kd70A2oQXHa06kPy7IgCeCvr5Efj9VmuhgJUfn+
    QxXN3boC4lzL5HymNi2CJ4wMG2B7s79E9PcWiD0Ci6tcpBJWI6Wd+uqcNtWQQq1X
    GCx0pLcEUk7wY8eliVhq2SrQFrYRngsUstivmvvJkdypY95gpI0nMYoRORQEufhB
    TOARR78W5pgOrIUslASzdEEygO3rFPUqHERY3ciO9cGnIxVeF+Yvp8sWdg46W5+V
    Iqn+GJ4cYa/VqOEU8rqw83ianj8YyQIDAQABAoICAAquSV49feT1yEBFM2PHCee6
    cdEO1fnwVdHvmmytYnyjsT0+VT/scG8kAOstT3iIveN78hCZgjlSm8lOeZA4nsUi
    USqCnzjHOjF31N/mBOr4uCeKzAUfg4Zdw/kbvWohyivJNfAyQRkKbFU3mc1KeaRz
    +HQeXxXnEgrIZ1uEUcYFHKyAqvs2LeEDTfHG8FiSTKR72+tq+1yKitcxnHLepnEn
    ve94hXAFPRXztd2reiwV6K88ccbcn8eF9EjqJivhvEgt58/9eWbOJqjC0TGfh8zy
    4V00TaRNdTSop4rm4t520u5HbhFP+/AzGmQ3OsZUx9vR2mrUBFFotTPu+654hVAK
    uhnRCLceGrhfIhN3eK7u3GQ1C3Y0542HnuMANdOvcETELgiDBwAgZErFr0COZ93p
    Cz3VDm6XQlet8AXLmFs11zhlnqhL680sXL/LEX8VVXehC7DMttEwGxLtbx8cwaZ0
    miCxphYlcV261vAXcv7wQ8QX8ORHdjVFa7uE9dK0QFxtmz8VUVg9MrkcNIR86vQR
    XwzxZAeVyIvWHfg5yGDMewYalxn87vkRuYPfBQqV1sRXI3+hg/ibVQftsOJJ5zUv
    NhqZdT/OE/vNDAIQ+fUu5I/jLAtbOSjTgKCKwp5HKEV00McC+yT9bxDyD5HAjF3/
    RygsCG1k4qIZq2XUXa6nAoIBAQDxN9ewSHbe2mnsphviRlveIyOvDz3YGRm4vG4j
    qCEHQKnWx30BQVQxYOhpiG9kPcHBjQAA6LFvutJRuij9QVVuMDxDhbPweJTiS/G3
    udJ95XZ947uqPzxu8Txpk+BMsW6/FIsf8AI55acQn6HmTe/Si0hUxCFonRr1SfuU
    W8ga7jdqzI5U/FxTOJ43iCn5yY+ZEPOeI/FT3mCmYgg1ZuaMQKvYxvmpgy06Up+1
    nUm82DypOMPq5Uy6GPKF2T1lVmFOZWhzues8UsUnhrITNmucvxJ3xCroB/Cz7lDv
    3bITyA4MbUJRb0eOsEEPUORo8ewXgVo5fbjlt6Kbl4PF6LODAoIBAQDc0okEtL9L
    vDzga2W1NbSKhp/Xlm0Q6QttBIX8AsahYP6Y04q5U8a0nvbtjiRGx9QSCuKbyiLR
    Nt/kRz4npmpLtqu8C2IPE6HsgyYnipOSPs7Jk+D7teew9KpSmRvA5ALTZn3J2tHO
    R5bKUettVr/vWqRJrcxFZQbNaQgG5d/ErniWaEwCgwhKfsGO1Cdz6h8ae+SdsOvP
    s2t8zXKBpgaXmAPM2dMpV2HCHjpKb3zIExwHCuR+n2HmJ21QKofua3evDjNzlvhK
    bq8MgVhKACHYPRWlccUURAhMI95OeRlYYLGs88oKaBXZeUmDkDVJl+FUOiquxMSl
    gafbWR5FDXTDAoIBAAfiSVxroeb6wIeJjlPA9PO3tkzcdKsBdwPAtODZd+rixCpO
    7tkBp5zNjAsW+H0QP6rxztQ4xsPeGU2uhfRxFDe7v9x9HDp51nPnA4l7u1N+Ende
    4B1aX8FIhS72NFiNXA9Gvp1WnNwDk4hJj2MVnQcGomCS4Hyo1d66gkyBC3NF4e3N
    rcE9Vk8qBJHQE38khVr9YNkEV7jkBciqX5ZPPK3M11EIf9R4gxvq42luMKDJeIIX
    Zt/girdyZUrWpNkRD7EeQ2G06+lW0zbNgjh6iN3gqNvdP4HB8K4Q1fhhCJb47Oyf
    DZHXz0DspdO4Ux7S+WJzSd2jLE3lyJzJQPdQ+b0CggEBAMrCRi2cCUpxPTSTaIBL
    H8tScdJyvRKZ6XPgg2Yy5k+n0B5jny0sT3fpvrHBom2bbo5ikFCb+fxAdrQU9m1R
    0KhUwruXeCJ/1F5mzdHg3D+cjCNrNVnqXSOOhBXzoBgtRKr3oOiHk73k3gBH1/Q9
    g18zy0Yb30SYzvYtSsGKsTzXNsJkYeasiiBc4z1ScCdvAcA/olto6B1+kWO3AT0q
    RUNMwbCHEe0T3x9uwfc3B0xuv3138vaRQkMiUK0bYFT7OJn0YCnypWky2GiTG45X
    MLxs2kNfg6ZoEXZYOPe1GiCcKIi2EP4dNHLLe0TiVQuN+chs4GQ5KJcPxiESY0jk
    YiECggEBAOJIYf70i46jW+blyMrQen17tq0Od0HqSfqXd3Dw7dcPs6yDaVZLuT0+
    2dkyX/WVpAvqH02n+9uv3DOYB9ST5nAKwVWN6GIAx6WFEimO8El3DbCs6Mqw4bD+
    coHOIYQzGeW6r8xWTNhfmB/IW1jYyjmI/zjvLTHILGw95vQII29DakKMJJ2dD5iF
    F7K3kweYBuIHacIX6fi+0dt6ifkDnYeCJJ3lqEhTgeYmBOUSNJkKzf4NJq1ROqTB
    ADjaXISf+zHVsNB4mZmtl/MEEdyD+ypMDXXsNKBjvb6xE9y4VBqsUxyGfGLZBbJY
    tuZTaziXHkDSbcGJC5X9bSW0tFgDSKU=
    -----END PRIVATE KEY-----
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: proxy
  name: proxy-cm1-certs