apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: 'yes'
    pv.kubernetes.io/bound-by-controller: 'yes'
    volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
    volume.kubernetes.io/selected-node: k8sc2
    volume.kubernetes.io/storage-provisioner: rancher.io/local-path
  finalizers:
    - kubernetes.io/pvc-protection
  name: registry-data
  namespace: default
  resourceVersion: '58079'
  uid: cf1cfb5e-143c-4098-9b9b-5a211343516d
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: local-path
  volumeMode: Filesystem
  volumeName: pvc-cf1cfb5e-143c-4098-9b9b-5a211343516d
status:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 20Gi
  phase: Bound